// ERROR
export default function addStoreErrMsg() {
  return function(input) {
    switch (input) {
      case 'S400':
        return '参数不正确';
      case 'S404':
        return '资源不存在';
      case 'S405':
        return 'http method不支持';
      case 'S409':
        return '门店或企业或品牌名称重复或已经存在';
      case 'S500':
        return '业务错误';
      case 'CRM_001':
        return '数据不存在';
      case 'CRM_002':
        return '关联数据的不存在';
      case 'CRM_003':
        return '无效的配置信息代码';
      case 'CRM_004':
        return '参数中省市区数据不完整';
      case 'CRM_005':
        return '没有操作此数据的权限';
      case 'CRM_006':
        return '没有查看此数据的权限';
      case 'CRM_007':
        return '数据转换异常';
      case 'CRM_008':
        return '门店名称重复';
      case 'CRM_009':
        return '参数中省市区数据不能识别';
      case 'CRM_010':
        return '必传参数缺失';
      case 'CRM_011':
        return '参数格式不正确';
      case 'CRM_012':
        return '存在关联数据不能删除';
      case 'CRM_013':
        return '数据当前状态与操作不对应';
      case 'CRM_014':
        return '无效的状态参数';
      case 'CRM_015':
        return '不能重复上线该业务';
      case 'CRM_016':
        return '不能修改主键字段';
      case 'CRM_17':
        return '不能重复生成';
      case 'CRM_018':
        return '企业名称不能为空';
      case 'CRM_019':
        return '信息同步失败';
      case 'CRM_020':
        return '业务未上线';
      case 'CRM_021':
        return '不能重复提交该业务';
      case 'CRM_022':
        return '企业名称重复';
      case 'CRM_023':
        return '品牌名称重复';
      case 'CRM_040':
        return '银行卡号长度必须在16到19之间';
      case 'CRM_041':
        return '银行卡必须全部为数字';
      case 'CRM_042':
        return '银行卡不符合规则';
      case 'CRM_43':
        return '该品牌对象在数据库中不存在或者属性没有对应(brandId存在)';
      case 'CRM_044':
        return '该公司对象在数据库中不存在或者属性没有对应(companyId存在)';
      case 'CRM_045':
        return '品牌ID存在的，企业ID不存在，这种逻辑不存在';
      case 'CRM_046':
        return '品牌名称与正式库名称重复(brandId不存在)';
      case 'CRM_047':
        return '公司名称与正式库名称重复(companyId不存在)';
      case 'CRM_048':
        return '该业务类型(businessId)在数据库中不存在或者没有上线';
      case 'CRM_049':
        return '门店ID(storeId)在数据库中不存在';
      case 'CRM_050':
        return '操作者Id和跟进人Id不相同，无权操作';
      case 'CRM_051':
        return '该门店状态不是GET，REJECT，不能提交';
      case 'CRM_052':
        return '该门店ID和业务ID在门店关联表中不存在';
      case 'CRM_053':
        return '该门店不是私海';
      case 'CRM_054':
        return '一个storeId在已提交状态，不能再次提交了';
      case 'CRM_055':
        return '门店名称已经在数据库中已经存在';
      case 'CRM_056':
        return '省市区代码不对应';
      case 'CRM_057':
        return '该门店存在尚未通过的快餐进件';
      case 'CRM_058':
        return '快餐进件中门店信息不能被修改';
      case 'CRM_059':
        return '该门店的快餐进件已审核通过，不能重复审核';
      case 'CRM_060':
        return '该门店的快餐进件已驳回，不能重复驳回';
      case 'CRM_061':
        return '门店信息有误';
      case 'CRM_062':
        return '门店名称，企业名称，品牌名称互不重复';
      case 'CRM_063':
        return '若新建联系人，则联系人名称必填';
      case 'CRM_064':
        return '修改门店私海失败';
      case 'CRM_065':
        return '门店或企业业务类型不符合规定'; 
      default:
        return '';
    }
  };
}